name: Build VoiceInk (Tauri) & Package DMG

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install frontend dependencies
        run: npm ci

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build VoiceInk with Tauri
        run: npm run tauri build

      - name: Copy DMG artifact
        run: |
          mkdir -p output
          cp src-tauri/target/release/bundle/dmg/*.dmg output/

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: VoiceInk-macOS-DMG
          path: output/*.dmg
