name: Build and Package VoiceInk (SwiftPM)

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Swift Package Manager
        run: |
          swift build --configuration release
          mkdir -p dist
          cp -R .build/release/VoiceInk.app dist/

      - name: Create DMG
        run: |
          mkdir -p dmg_source
          cp -R dist/VoiceInk.app dmg_source/
          ln -s /Applications dmg_source/Applications
          hdiutil create -volname "VoiceInk" \
                         -srcfolder dmg_source \
                         -ov \
                         -format UDZO \
                         dist/VoiceInk.dmg

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: VoiceInk-macOS-DMG
          path: dist/VoiceInk.dmg
