name: Build VoiceInk macOS app

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-macos:
    runs-on: macos-14

    permissions:
      contents: write

    steps:
      # 1. Check out your repository
      - uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      # 3. Set up Rust with both Apple Silicon and Intel targets
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      # 4. Cache Rust build artifacts
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: './VoiceInk/src-tauri -> ./VoiceInk/src-tauri/target'

      # 5. Install Node.js dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: VoiceInk

      # 6. Install Tauri CLI
      - name: Install Tauri CLI
        run: cargo install --locked tauri-cli
        working-directory: VoiceInk

      # 7. Build for x86_64 and aarch64
      - name: Build VoiceInk for macOS
        run: |
          rustup target add x86_64-apple-darwin
          npm exec tauri build -- --target x86_64-apple-darwin
          npm exec tauri build -- --target aarch64-apple-darwin
        working-directory: VoiceInk

      # 8. Upload DMG artifacts
      - name: Upload DMG artifacts
        uses: actions/upload-artifact@v4
        with:
          name: voiceink-macos-dmg
          path: |
            VoiceInk/src-tauri/target/*-apple-darwin/release/bundle/dmg/*.dmg
          if-no-files-found: error
