name: Build VoiceInk macOS App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Use Xcode 15.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Checkout VoiceInk
        uses: actions/checkout@v4

      - name: Fetch whisper.cpp and build XCFramework
        run: |
          cd ..
          git clone https://github.com/ggerganov/whisper.cpp
          cd whisper.cpp
          ./build-xcframework.sh

      - name: Resolve Swift Package dependencies
        run: |
          xcodebuild \
            -project VoiceInk.xcodeproj \
            -resolvePackageDependencies \
            -disableAutomaticPackageResolution

      - name: Build VoiceInk app
        run: |
          xcodebuild \
            -project VoiceInk.xcodeproj \
            -scheme VoiceInk \
            -configuration Release \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            clean build

      - name: Package into DMG
        run: |
          mkdir -p dmg-out
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "VoiceInk.app" -type d | head -n 1)
          cp -R "$APP_PATH" dmg-out/
          hdiutil create -volname VoiceInk \
                         -srcfolder dmg-out \
                         -ov \
                         -format UDZO \
                         VoiceInk.dmg

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: VoiceInk-macOS
          path: VoiceInk.dmg
