name: Build VoiceInk macOS app

on:
  workflow_dispatch:
  push:
    branches: [main]      # adjust branch as needed

jobs:
  build-macos:
    runs-on: macos-14     # GitHub runner with macOS 14

    permissions:
      contents: write     # allows tauri to embed version info and enables artifact upload

    steps:
      # 1. Check out your repository
      - uses: actions/checkout@v4

      # 2. Set up Node.js (LTS) with caching
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      # 3. Install the Rust toolchain with both Intel and Apple Silicon targets
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      # 4. Cache Rust build artifacts
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      # 5. Install JavaScript/TypeScript dependencies
      - name: Install dependencies
        run: npm ci

      # 6. Install the Tauri CLI (optional, for consistency)
      - name: Install Tauri CLI
        run: cargo install --locked tauri-cli

      # 7. Build the app for both architectures
      - name: Build VoiceInk for macOS
        run: |
          rustup target add x86_64-apple-darwin
          npm exec tauri build -- --target x86_64-apple-darwin
          npm exec tauri build -- --target aarch64-apple-darwin
        env:
          # Uncomment and set these when you're ready for signing
          # TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          # TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

      # 8. Upload generated .dmg files as an artifact
      - name: Upload DMG artifacts
        uses: actions/upload-artifact@v4
        with:
          name: voiceink-macos-dmg
          path: |
            src-tauri/target/*-apple-darwin/release/bundle/dmg/*.dmg
          if-no-files-found: error
