name: Build VoiceInk with Xcode 15.4

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15  # Sequoia: includes Xcode 15.4 and Xcode 16

    steps:
      - name: Set up Xcode 15.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Check active Xcode
        run: xcodebuild -version

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build whisper.xcframework
        run: |
          cd ..
          git clone https://github.com/ggerganov/whisper.cpp
          cd whisper.cpp
          ./build-xcframework.sh

      - name: Resolve Swift packages
        run: xcodebuild -project VoiceInk.xcodeproj -resolvePackageDependencies

      - name: Build VoiceInk
        run: xcodebuild -project VoiceInk.xcodeproj \
                        -scheme VoiceInk \
                        -configuration Release \
                        CODE_SIGNING_REQUIRED=NO \
                        CODE_SIGNING_ALLOWED=NO \
                        CODE_SIGN_IDENTITY="" clean build

      - name: Package DMG
        run: |
          mkdir dmg-out
          APP=$(find ~/Library/Developer/Xcode/DerivedData -name VoiceInk.app | head -n1)
          cp -R "$APP" dmg-out/
          hdiutil create -volname VoiceInk -srcfolder dmg-out -ov -format UDZO VoiceInk.dmg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VoiceInk-macOS
          path: VoiceInk.dmg
